version: "3.9"

services:
  src:
    container_name: cutlang
    image: shenburak/cutlang
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - "80:80"
