version: "3.9"

services:
  src:
    container_name: cutlang
    image: cutlang/cutlang
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - "8888:8888"
