name: Tests

on: [push, pull_request]

jobs:
  build:
    
    runs-on: ubuntu-latest
    container: rootproject/root:6.24.00-ubuntu20.04

    steps:
    - uses: actions/checkout@v2
        
    - name: init-cache-dir
      run: mkdir build ; chmod +x ./.github/workflows/sendgrid.js
      
    - name: Build CutLang
      run: cd ./CLA ; make
    
    - name: Run Tests
      run: |
        cd $HOME/work/CutLang/CutLang/.github/workflows ; chmod +x deploy.sh ; ./deploy.sh 2>&1 | tee ./raw_output.txt
      
    - name: Filter Output
      run: |
        cd $HOME/work/CutLang/CutLang/.github/workflows ; chmod +x filter.sh ; ./filter.sh
        cd $HOME/work/CutLang/CutLang/.github/previous ; diff raw_output.txt ../workflows/raw_output.txt | tee ../workflows/differences.txt ; rm raw_output.txt errors.txt efficacy_charts.txt differences.txt 
        cd $HOME/work/CutLang/CutLang/.github/workflows ; cp raw_output.txt errors.txt efficacy_charts.txt differences.txt ../previous/
        cd $HOME/work/CutLang/CutLang/.github/workflows ; mkdir artifacts ; mv raw_output.txt errors.txt efficacy_charts.txt differences.txt ./artifacts
        if [ "`cat $HOME/work/CutLang/CutLang/.github/workflows/artifacts/errors.txt`" != "Errors: " ]; then
          touch flag
        fi
        chmod +x mail_body.sh ; ./mail_body.sh

    - name: Check for Bad Run Flag
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "flag"

    - name: SMTP
      uses: peter-evans/sendgrid-action@v1
      if: steps.check_files.outputs.files_exists == 'true'
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        SCRIPT_FILEPATH: ./.github/workflows/sendgrid.js     
        
    - name: Clear Temporary Files
      run: rm $HOME/work/CutLang/CutLang/.github/workflows/artifacts/temp.txt ; rm -f flag 

    - name: Update Artifacts
      if: steps.cache.outputs.cache-hit == 'true'
      run: cd $HOME/work/CutLang/CutLang/.github/workflows ; chmod +x commit.sh ; ./commit.sh ${GITHUB_REF##*/}
      
    - name: Upload Output File
      uses: actions/upload-artifact@v1.0.0
      with:
        name: tests (ubuntu-latest)
        path: ./.github/workflows/artifacts
